import { RoadSegment } from '../../types';
import { getMergedCanonicalGeometry } from './canonical-road-network';

export const MAJOR_HCMC_ROADS: RoadSegment[] = [
  {
    id: 'road-nguyen-huu-canh',
    properties: {
      id: 'road-nguyen-huu-canh',
      roadId: 'nguyen-huu-canh',
      roadName: 'Nguyễn Hữu Cảnh',
      district: 'Bình Thạnh',
      anchorPoint: [106.7175, 10.7935],
      labelPoint: [106.7175, 10.7935],
      estimatedDepthCm: 28,
      riskLevel: 'warning',
      rain1hMm: 18,
      rain3hMm: 46,
      tideImpactM: 0.42,
      drainageMinutes: 90,
      confidenceBand: 'medium',
      confidenceScore: 0.78,
      isSimulated: true,
      reasonTags: ['heavy-rain-3h', 'low-elevation', 'slow-drainage'],
      reasons: [
        'Mưa tích lũy 3 giờ cao (46 mm)',
        'Đoạn trũng chân cầu Thủ Thiêm',
        'Cống thoát nước áp lực ra sông Sài Gòn',
      ],
      advice: 'Hạn chế xe gầm thấp lưu thông qua đoạn ngập > 20 cm. Ưu tiên hướng Điện Biên Phủ.',
      updatedAt: '14:32',
      lowElevationScore: 0.88,
      poorDrainageScore: 0.82,
      historicalFloodScore: 0.92,
      segmentIds: ['seg-nhc-1', 'seg-nhc-2'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['seg-nhc-1', 'seg-nhc-2']),
  },
  {
    id: 'road-quoc-huong-thao-dien',
    properties: {
      id: 'road-quoc-huong-thao-dien',
      roadId: 'quoc-huong',
      roadName: 'Quốc Hương · Thảo Điền',
      district: 'Thủ Đức',
      anchorPoint: [106.7365, 10.8085],
      labelPoint: [106.7365, 10.8085],
      estimatedDepthCm: 35,
      riskLevel: 'severe',
      rain1hMm: 22,
      rain3hMm: 55,
      tideImpactM: 0.65,
      drainageMinutes: 140,
      confidenceBand: 'high',
      confidenceScore: 0.84,
      isSimulated: true,
      reasonTags: ['tide-surge', 'peninsula-basin', 'heavy-rain'],
      reasons: [
        'Triều cường sông Sài Gòn dâng cao (+0.65 m)',
        'Địa hình bán đảo trũng cục bộ',
        'Mưa dông tích lũy lớn trong 3 giờ',
      ],
      advice: 'Nước ngập sâu trên 30 cm. Xe máy và ô tô con tuyệt đối không đi qua đoạn ngập.',
      updatedAt: '14:32',
      lowElevationScore: 0.92,
      poorDrainageScore: 0.85,
      historicalFloodScore: 0.9,
      segmentIds: ['seg-quoc-huong-1', 'seg-quoc-huong-2'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['seg-quoc-huong-1', 'seg-quoc-huong-2']),
  },
  {
    id: 'road-vo-van-ngan',
    properties: {
      id: 'road-vo-van-ngan',
      roadId: 'vo-van-ngan',
      roadName: 'Võ Văn Ngân (Chợ Thủ Đức)',
      district: 'Thủ Đức',
      anchorPoint: [106.761, 10.8495],
      labelPoint: [106.761, 10.8495],
      estimatedDepthCm: 22,
      riskLevel: 'warning',
      rain1hMm: 25,
      rain3hMm: 42,
      tideImpactM: 0.2,
      drainageMinutes: 60,
      confidenceBand: 'high',
      confidenceScore: 0.82,
      isSimulated: true,
      reasonTags: ['steep-slope-flow', 'market-basin', 'fast-runoff'],
      reasons: [
        'Độ dốc lớn tạo dòng chảy xiết dồn về chợ',
        'Cửa xả rạch Cầu Ngang quá tải tức thời',
        'Lượng mưa giờ đầu tiên đạt 25 mm/h',
      ],
      advice: 'Chú ý dòng nước chảy xiết tại khu vực dốc chợ Thủ Đức. Giữ khoảng cách an toàn.',
      updatedAt: '14:32',
      lowElevationScore: 0.7,
      poorDrainageScore: 0.75,
      historicalFloodScore: 0.85,
      segmentIds: ['canon-vo-van-ngan'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-vo-van-ngan']),
  },
  {
    id: 'road-huynh-tan-phat',
    properties: {
      id: 'road-huynh-tan-phat',
      roadId: 'huynh-tan-phat',
      roadName: 'Huỳnh Tấn Phát',
      district: 'Quận 7',
      anchorPoint: [106.727, 10.744],
      labelPoint: [106.727, 10.744],
      estimatedDepthCm: 32,
      riskLevel: 'severe',
      rain1hMm: 16,
      rain3hMm: 38,
      tideImpactM: 0.75,
      drainageMinutes: 150,
      confidenceBand: 'medium',
      confidenceScore: 0.76,
      isSimulated: true,
      reasonTags: ['tidal-flooding', 'riverbank-proximity'],
      reasons: [
        'Triều cường kết hợp mưa lớn làm tràn bờ',
        'Khu vực hạ lưu sông Soài Rạp',
        'Nước rút chậm do triều đang dâng',
      ],
      advice: 'Ngập sâu diện rộng. Chuyển hướng lưu thông sang đường Nguyễn Lương Bằng.',
      updatedAt: '14:32',
      lowElevationScore: 0.94,
      poorDrainageScore: 0.88,
      historicalFloodScore: 0.95,
      segmentIds: ['canon-huynh-tan-phat'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-huynh-tan-phat']),
  },
  {
    id: 'road-tran-xuan-soan',
    properties: {
      id: 'road-tran-xuan-soan',
      roadId: 'tran-xuan-soan',
      roadName: 'Trần Xuân Soạn (Bờ Kênh Tẻ)',
      district: 'Quận 7',
      anchorPoint: [106.7155, 10.7525],
      labelPoint: [106.7155, 10.7525],
      estimatedDepthCm: 38,
      riskLevel: 'severe',
      rain1hMm: 14,
      rain3hMm: 32,
      tideImpactM: 0.82,
      drainageMinutes: 180,
      confidenceBand: 'high',
      confidenceScore: 0.85,
      isSimulated: true,
      reasonTags: ['canal-overflow', 'king-tide'],
      reasons: [
        'Kênh Tẻ tràn bờ do đỉnh triều cường đạt 0.82 m',
        'Tuyến đường song song mặt nước không có đê bao khép kín',
        'Nước tràn ngược qua hệ thống cống',
      ],
      advice: 'Đường ngập sâu 35–40 cm dọc bờ kè. Tuyệt đối không di chuyển sát mép kênh.',
      updatedAt: '14:32',
      lowElevationScore: 0.96,
      poorDrainageScore: 0.9,
      historicalFloodScore: 0.98,
      segmentIds: ['seg-tran-xuan-soan', 'seg-txs-htp'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['seg-tran-xuan-soan', 'seg-txs-htp']),
  },
  {
    id: 'road-me-coc',
    properties: {
      id: 'road-me-coc',
      roadId: 'me-coc',
      roadName: 'Mễ Cốc · Bến Phú Định',
      district: 'Quận 8',
      anchorPoint: [106.636, 10.727],
      labelPoint: [106.636, 10.727],
      estimatedDepthCm: 42,
      riskLevel: 'severe',
      rain1hMm: 15,
      rain3hMm: 36,
      tideImpactM: 0.88,
      drainageMinutes: 200,
      confidenceBand: 'medium',
      confidenceScore: 0.74,
      isSimulated: true,
      reasonTags: ['dyke-risk', 'tidal-surge', 'lowest-elevation'],
      reasons: [
        'Vùng đất thấp trũng nhất lưu vực Tàu Hủ - Bến Nghé',
        'Triều cường đạt mức báo động 3',
        'Áp lực dòng chảy từ thượng nguồn dồn về',
      ],
      advice: 'Ngập sâu nguy hiểm. Không lưu thông xe qua khu vực Mễ Cốc khi đỉnh triều.',
      updatedAt: '14:32',
      lowElevationScore: 0.98,
      poorDrainageScore: 0.92,
      historicalFloodScore: 0.96,
      segmentIds: ['canon-me-coc'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-me-coc']),
  },
  {
    id: 'road-phan-thuc-duyen',
    properties: {
      id: 'road-phan-thuc-duyen',
      roadId: 'phan-thuc-duyen',
      roadName: 'Phan Thúc Duyện · Trường Sơn',
      district: 'Tân Bình',
      anchorPoint: [106.658, 10.8035],
      labelPoint: [106.658, 10.8035],
      estimatedDepthCm: 14,
      riskLevel: 'watch',
      rain1hMm: 12,
      rain3hMm: 28,
      tideImpactM: 0.1,
      drainageMinutes: 45,
      confidenceBand: 'high',
      confidenceScore: 0.82,
      isSimulated: true,
      reasonTags: ['airport-corridor', 'moderate-rain'],
      reasons: [
        'Mưa rào nặng hạt quanh khu vực sân bay TSN',
        'Đoạn đường gom trước công viên Hoàng Văn Thụ ứ đọng nhẹ',
      ],
      advice: 'Giao thông di chuyển chậm. Xe máy chú ý giảm tốc độ qua các vũng đọng nước.',
      updatedAt: '14:32',
      lowElevationScore: 0.55,
      poorDrainageScore: 0.65,
      historicalFloodScore: 0.65,
      segmentIds: ['seg-lang-cha-ca-ptd', 'canon-truong-son-airport'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['seg-lang-cha-ca-ptd', 'canon-truong-son-airport']),
  },
  {
    id: 'road-le-duc-tho',
    properties: {
      id: 'road-le-duc-tho',
      roadId: 'le-duc-tho',
      roadName: 'Lê Đức Thọ',
      district: 'Gò Vấp',
      anchorPoint: [106.6605, 10.8455],
      labelPoint: [106.6605, 10.8455],
      estimatedDepthCm: 18,
      riskLevel: 'warning',
      rain1hMm: 16,
      rain3hMm: 34,
      tideImpactM: 0.15,
      drainageMinutes: 70,
      confidenceBand: 'medium',
      confidenceScore: 0.72,
      isSimulated: true,
      reasonTags: ['bottleneck-drainage', 'urban-runoff'],
      reasons: [
        'Cống thoát nước khu vực giao cắt Lê Văn Thọ bị nghẽn cục bộ',
        'Lượng nước mặt từ các hẻm dồn ra trục đường chính',
      ],
      advice: 'Hạn chế di chuyển vào làn sát lề đường nơi nước đọng sâu.',
      updatedAt: '14:32',
      lowElevationScore: 0.62,
      poorDrainageScore: 0.78,
      historicalFloodScore: 0.75,
      segmentIds: ['canon-le-duc-tho'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-le-duc-tho']),
  },
  {
    id: 'road-kinh-duong-vuong',
    properties: {
      id: 'road-kinh-duong-vuong',
      roadId: 'kinh-duong-vuong',
      roadName: 'Kinh Dương Vương (Bến xe Miền Tây)',
      district: 'Bình Tân',
      anchorPoint: [106.617, 10.7415],
      labelPoint: [106.617, 10.7415],
      estimatedDepthCm: 24,
      riskLevel: 'warning',
      rain1hMm: 15,
      rain3hMm: 35,
      tideImpactM: 0.35,
      drainageMinutes: 80,
      confidenceBand: 'high',
      confidenceScore: 0.81,
      isSimulated: true,
      reasonTags: ['major-artery', 'gateway-basin'],
      reasons: [
        'Trục cửa ngõ miền Tây chịu áp lực nước từ các khu dân cư lân cận',
        'Hệ thống trạm bơm đang vận hành công suất cao',
      ],
      advice: 'Xe buýt và xe lớn lưu thông bình thường; xe máy nên đi làn giữa.',
      updatedAt: '14:32',
      lowElevationScore: 0.75,
      poorDrainageScore: 0.8,
      historicalFloodScore: 0.82,
      segmentIds: ['canon-kinh-duong-vuong'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-kinh-duong-vuong']),
  },
  {
    id: 'road-calmette-co-giang',
    properties: {
      id: 'road-calmette-co-giang',
      roadId: 'calmette',
      roadName: 'Calmette · Cô Giang',
      district: 'Quận 1',
      anchorPoint: [106.7, 10.7695],
      labelPoint: [106.7, 10.7695],
      estimatedDepthCm: 4,
      riskLevel: 'safe',
      rain1hMm: 8,
      rain3hMm: 18,
      tideImpactM: 0.25,
      drainageMinutes: 20,
      confidenceBand: 'high',
      confidenceScore: 0.88,
      isSimulated: true,
      reasonTags: ['central-district', 'good-drainage'],
      reasons: [
        'Hệ thống cống trung tâm thoát nước tốt ra kênh Bến Nghé',
        'Lượng mưa tích lũy không vượt ngưỡng báo động',
      ],
      advice: 'Tuyến đường thông suốt, an toàn cho mọi phương tiện.',
      updatedAt: '14:32',
      lowElevationScore: 0.4,
      poorDrainageScore: 0.35,
      historicalFloodScore: 0.45,
      segmentIds: ['canon-calmette-co-giang'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-calmette-co-giang']),
  },
  {
    id: 'road-doan-van-bo',
    properties: {
      id: 'road-doan-van-bo',
      roadId: 'doan-van-bo',
      roadName: 'Đoàn Văn Bơ · Tôn Thất Thuyết',
      district: 'Quận 4',
      anchorPoint: [106.7042, 10.758],
      labelPoint: [106.7042, 10.758],
      estimatedDepthCm: 16,
      riskLevel: 'warning',
      rain1hMm: 14,
      rain3hMm: 30,
      tideImpactM: 0.45,
      drainageMinutes: 65,
      confidenceBand: 'medium',
      confidenceScore: 0.75,
      isSimulated: true,
      reasonTags: ['island-district', 'narrow-street'],
      reasons: [
        'Mặt đường hẹp, hệ thống thoát nước cũ',
        'Chịu ảnh hưởng bởi mực nước kênh Tẻ dâng cao',
      ],
      advice: 'Chú ý tránh các nắp hố ga và đoạn trũng gần bờ kè Tôn Thất Thuyết.',
      updatedAt: '14:32',
      lowElevationScore: 0.72,
      poorDrainageScore: 0.74,
      historicalFloodScore: 0.78,
      segmentIds: ['seg-doan-van-bo'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['seg-doan-van-bo']),
  },
  {
    id: 'road-pham-van-chieu',
    properties: {
      id: 'road-pham-van-chieu',
      roadId: 'pham-van-chieu',
      roadName: 'Phạm Văn Chiêu',
      district: 'Gò Vấp',
      anchorPoint: [106.657, 10.8485],
      labelPoint: [106.657, 10.8485],
      estimatedDepthCm: 26,
      riskLevel: 'warning',
      rain1hMm: 20,
      rain3hMm: 44,
      tideImpactM: 0.15,
      drainageMinutes: 85,
      confidenceBand: 'high',
      confidenceScore: 0.8,
      isSimulated: true,
      reasonTags: ['chronic-flood-point', 'heavy-rain'],
      reasons: [
        'Lịch sử ghi nhận ngập mãn tính mỗi khi mưa trên 30 mm',
        'Địa hình lòng máng gom nước từ các khu phố lân cận',
      ],
      advice: 'Đoạn trước trường tiểu học ngập sâu. Khuyến nghị vòng sang đường Cây Trâm.',
      updatedAt: '14:32',
      lowElevationScore: 0.82,
      poorDrainageScore: 0.85,
      historicalFloodScore: 0.9,
      segmentIds: ['canon-pham-van-chieu'],
      geometryQuality: 'verified',
    },
    geometry: getMergedCanonicalGeometry(['canon-pham-van-chieu']),
  },
];
